### ISSUE TITLE
Clarify dkregistry's License

### ISSUE THREAD

**Issue by dpeckett** [camallo/dkregistry-rs#143]
At current it appears the only available license information for this crate is in the cargo toml. This should be made more prominent (eg. a license file and headers in source files).

**Comment by lucab** [comment]
Thanks for the report. Licensing is indeed as specified in the Cargo manifest, i.e. MIT or APL-2.0 at your option.

But it would indeed be better to make this more prominent. #164 is open to tackle that. No need for headers in each source file, a [machine-readable](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/) COPYRIGHT file is fine enough.

**Comment by dpeckett** [comment]
Thanks @lucab

**Comment by lucab** [comment]
(keeping this open until #164 lands)
